config/routes.rb
Rails.application.routes.draw do
  resources :reservations, :only => [:new, :create] do
    member do
      get :confirm
      put :confirmation

      get :customize
      put :customization

      get :rate
      put :rating
    end
  end

  root 'reservations#new'

end

app/models/amenity.rb
class Amenity < ActiveRecord::Base

  has_and_belongs_to_many :reservations

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  MAX_RATING = 5

  has_and_belongs_to_many :amenities

  # Validating emails is not an easy task and if the user needs to confirm it that seems like
  #  a sufficient validation.
  # See: http://davidcel.is/blog/2012/09/06/stop-validating-email-addresses-with-regex/
  validates_format_of :email, :with => /@/

  with_options :on => :update do |reservation|
    reservation.validate  :email_not_changed
    reservation.validates :first_name, :presence => true
    reservation.validates :last_name, :presence => true
    reservation.validates :phone_number, :presence => true,
                                         :numericality => { :only_integer => true }
  end

  with_options :on => :rate do |reservation|
    reservation.validates :rating, :presence => true,
                          :numericality => { :only_integer => true,
                                             :greater_than_or_equal_to => 1,
                                             :less_than_or_equal_to => MAX_RATING }
  end

  validate  :rating_not_changed


  def confirmed?
    first_name.present? && last_name.present? && phone_number.present?
  end

  def rated?
    rating.present?
  end

  private

  def email_not_changed
    if email_changed? && self.persisted?
      errors.add(:email, 'Change of email not allowed!')
    end
  end

  def rating_not_changed
    if rated? && rating_was && rating_changed? && persisted?
      errors.add(:rating, 'Change of rating not allowed!')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :set_reservation, only: [:confirm, :confirmation, :customize, :customization, :rate,
                                         :rating]

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # POST /reservations
  def create
    @reservation = Reservation.new(create_reservation_params)

    if @reservation.save
      ReservationMailer.confirmation_email(@reservation).deliver
      redirect_to new_reservation_path, notice: t('reservation.created')
    else
      render :new
    end
  end

  # GET /reservations/:id/confirm
  def confirm
    redirect_to rate_reservation_path(@reservation) if @reservation.confirmed?
  end

  # PUT /reservations/:id/confirmation
  def confirmation
    if @reservation.update(confirm_reservation_params)
      redirect_to customize_reservation_path(@reservation), notice: t('reservation.confirmed')
    else
      render :confirm
    end
  end

  # GET /reservations/:id/customize
  def customize

  end

  # PUT /reservations/:id/customization
  def customization
    @reservation.update(customize_reservation_params)
    ReservationMailer.completed_email(@reservation).deliver
    ReservationMailer.scheduled_email(@reservation).deliver

    redirect_to new_reservation_path, notice: t('reservation.completed')
  end

  # GET /reservations/:id/rate
  def rate

  end

  # PUT /reservations/:id/rating
  def rating
    @reservation.attributes = rate_reservation_params[:reservation]

    if @reservation.save(context: :rate)
      redirect_to rate_reservation_path(@reservation), notice: t('reservation.rated')
    else
      render :rate
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to new_reservation_path
  end

  def create_reservation_params
    params.require(:reservation).permit(:email)
  end

  def confirm_reservation_params
    params.require(:reservation).permit(:first_name, :last_name,
                                        :phone_number).merge(user_ip: request.remote_ip)
  end

  def customize_reservation_params
    params.require(:reservation).permit(:housing_date, :dark_wish, :amenity_ids => [])
  end

  def rate_reservation_params
    params[:reservation] ||= {}
    params.permit(:reservation => :rating)
  end

end

app/helpers/amenities_helper.rb
module AmenitiesHelper

  # Returns the amenities descriptions as a sentence
  #
  # @param [ActiveRecord::Relation <Amenity>] amenities
  #
  # @return [String]
  def amenities_to_sentence(amenities)
    amenities.pluck(:description).to_sentence
  end

end

app/helpers/date_helper.rb
module DateHelper

  def safe_l(date, *args)
    if date
      l(date, *args)
    else
      t('application.not_available')
    end
  end

end

app/views/application/_errors_explanation.html.haml
-# Partial used to render model error explanations.
-#
-# @param [String] model_name
-# @param [Array<ActiveModel::Errors>] errors
- if errors.any?
  #error_explanation
    %h2= t('application.errors_in_model', error_string: pluralize(errors.count, 'error'),
                                          model_name: model_name)

    %ul
      - errors.full_messages.each do |message|
        %li= message

app/views/application/_flash_notifications.html.haml
-# Partial used for render flash notifications.
- notices = Array(flash[:notice])
- if notices.any?
  .notice
    %ul
      - notices.each do |notice|
        %li= notice

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Siren

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    = render 'application/flash_notifications'
    = yield

app/views/reservations/_rate_form.html.haml
= form_for(reservation, url: rating_reservation_path(reservation), method: :put) do |f|
  = render 'application/errors_explanation', model_name: :reservation, errors: reservation.errors

  .field
    %strong
      = f.label :rating

    - 1.upto(Reservation::MAX_RATING) do |i|
      = f.radio_button(:rating, i)
      = label_tag("reservation_rating_#{i}", i)

  .actions
    = f.submit t('reservation.rate')

app/views/reservations/confirm.html.haml
%h1= t('reservation.confirm')

= form_for(@reservation, url: confirmation_reservation_path(@reservation), method: :put) do |f|
  = render 'application/errors_explanation', model_name: :reservation, errors: @reservation.errors

  .field
    = f.label :first_name
    = f.text_field :first_name

  .field
    = f.label :last_name
    = f.text_field :last_name

  .field
    = f.label :phone_number
    = f.text_field :phone_number

  .actions
    = f.submit t('reservation.confirm')

app/views/reservations/customize.html.haml
%h1= t('reservation.customize')

= form_for(@reservation, url: customization_reservation_path(@reservation), method: :put) do |f|
  = render 'application/errors_explanation', model_name: :reservation, errors: @reservation.errors

  .field
    = f.label :housing_date
    = f.date_select :housing_date

  .field
    = f.label :dark_wish
    = f.text_area :dark_wish

  .field
    = f.collection_check_boxes :amenity_ids, Amenity.all, :id, :description

  .actions
    = f.submit

app/views/reservations/new.html.haml
%h1= t('reservation.new')

= form_for(@reservation) do |f|
  = render 'application/errors_explanation', model_name: :reservation, errors: @reservation.errors

  .field
    = f.label :email
    = f.text_field :email

  .actions
    = f.submit

app/views/reservations/rate.html.haml
%h1= t('reservation.rate')

.field
  %strong
    = label_tag :first_name
  = @reservation.first_name

.field
  %strong
    = label_tag :last_name
  = @reservation.last_name

.field
  %strong
    = label_tag :phone_number
  = @reservation.phone_number

.field
  %strong
    = label_tag :housing_date
  = safe_l(@reservation.housing_date)

.field
  %strong
    = label_tag :dark_wish
  = @reservation.dark_wish

.field
  %strong
    = label_tag :amenities
  = amenities_to_sentence(@reservation.amenities)

- if @reservation.rated?
  .field
    %strong
      = label_tag :rating
    = @reservation.rating
- else
  = render 'rate_form', reservation: @reservation